# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(blank=True, db_column='Name', max_length=250, null=True)),
                ('url', models.CharField(blank=True, db_column='URL', max_length=500, null=True, unique=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=400, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('site', models.CharField(blank=True, db_column='SITE', max_length=200, null=True)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=200, null=True)),
                ('category1', models.CharField(blank=True, db_column='CATEGORY1', max_length=200, null=True)),
                ('category2', models.CharField(blank=True, db_column='CATEGORY2', max_length=200, null=True)),
                ('category3', models.CharField(blank=True, db_column='CATEGORY3', max_length=200, null=True)),
                ('category4', models.CharField(blank=True, db_column='CATEGORY4', max_length=200, null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('dateparsed', models.DateField(blank=True, db_column='DATEPARSED', null=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(db_column='FirstName', max_length=200)),
                ('SecondName', models.CharField(db_column='SecoondName', max_length=200)),
            ],
            options={
                'db_table': 'people',
            },
        ),
    ]
