# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='LastName',
            field=models.CharField(db_column='LastName', default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='people',
            name='SecondName',
            field=models.CharField(db_column='SecondName', max_length=200),
        ),
    ]
