# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20170413_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='telephone',
            field=models.CharField(blank=True, db_column='Telephone', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='category1',
            field=models.CharField(blank=True, db_column='Category1', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='category2',
            field=models.CharField(blank=True, db_column='Category2', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='category3',
            field=models.CharField(blank=True, db_column='Category3', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='category4',
            field=models.CharField(blank=True, db_column='Category4', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='dateparsed',
            field=models.DateField(blank=True, db_column='Dateparsed', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='site',
            field=models.CharField(blank=True, db_column='Site', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='url',
            field=models.CharField(blank=True, db_column='Url', max_length=500, null=True, unique=True),
        ),
    ]
