# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20170415_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfileUrl', models.CharField(blank=True, db_column='ProfileUrl', max_length=400, null=True)),
                ('Organization', models.CharField(blank=True, db_column='Organization', max_length=400, null=True)),
                ('Name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
            ],
            options={
                'db_table': 'avatars',
            },
        ),
        migrations.CreateModel(
            name='ParsingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameTask', models.CharField(db_column='Nametask', max_length=30)),
                ('Parametr', models.CharField(db_column='Parametr', max_length=200)),
                ('Starturl', models.CharField(db_column='Starturl', max_length=200, unique=True)),
                ('DateCreated', models.DateField(db_column='Datecreated')),
            ],
            options={
                'db_table': 'parsing',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Body', models.CharField(db_column='Body', max_length=200)),
                ('Url', models.CharField(db_column='Url', max_length=200, unique=True)),
                ('Type', models.CharField(db_column='Type', max_length=30)),
                ('DataCreated', models.DateField(db_column='DateCreated')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.People')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(db_column='Name', max_length=200)),
                ('Url', models.CharField(db_column='Url', max_length=200)),
                ('Type', models.CharField(db_column='Type', max_length=30)),
            ],
            options={
                'db_table': 'source',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='Inn',
            field=models.CharField(blank=True, db_column='Inn', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='Kpp',
            field=models.CharField(blank=True, db_column='Kpp', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='Ogrn',
            field=models.CharField(blank=True, db_column='Ogrn', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='parsingplan',
            name='Source_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Source'),
        ),
        migrations.AddField(
            model_name='avatars',
            name='Company_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.Company'),
        ),
        migrations.AddField(
            model_name='avatars',
            name='ParsingUrl_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.ParsingPlan'),
        ),
        migrations.AddField(
            model_name='avatars',
            name='People_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.People'),
        ),
    ]
