# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20170418_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatars',
            name='DateCreated',
            field=models.DateField(blank=True, db_column='Datecreated', null=True),
        ),
        migrations.AddField(
            model_name='avatars',
            name='DateParsed',
            field=models.DateField(blank=True, db_column='Dateparsed', null=True),
        ),
    ]
