# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20170418_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatars',
            name='Url',
            field=models.CharField(blank=True, db_column='Url', max_length=400, null=True),
        ),
    ]
