# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_auto_20170419_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatars',
            name='ProfileUrl',
            field=models.CharField(blank=True, db_column='ProfileUrl', max_length=400, null=True, unique=True),
        ),
    ]
