# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0016_auto_20170419_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatars',
            name='DateCreated',
            field=models.DateTimeField(auto_now_add=True, db_column='Datecreated'),
        ),
    ]
