# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0017_auto_20170419_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatars',
            name='DateCreated',
            field=models.DateTimeField(auto_now_add=True, db_column='Datecreated', null=True),
        ),
    ]
