# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0019_auto_20170503_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='Description',
        ),
        migrations.AddField(
            model_name='sources',
            name='Description',
            field=models.TextField(blank=True, db_column='Description', null=True),
        ),
        migrations.AlterField(
            model_name='sources',
            name='Type',
            field=models.CharField(db_column='Type', default='', max_length=30),
            preserve_default=False,
        ),
    ]
